FROM python:3.11.8
WORKDIR /code

 
COPY ./requirements.txt /code/requirements.txt

 
RUN apt-get update && apt-get upgrade -y
RUN pip install -r /code/requirements.txt
# 
WORKDIR /code

# 
COPY ./app /code/app
COPY ./tests /code/tests

COPY ./.git /code/.git

# INFO, DEBUG, DEBUG_PII
ENV LOGLEVEL="INFO"
ENV OPENBLAS_NUM_THREADS=1

WORKDIR /code/tests
