FROM continuumio/miniconda3

RUN apt-get update && apt-get install -y build-essential

# Create conda environment and install packages
RUN conda create -n py39 python=3.9 pip && \
    /bin/bash -c "source activate py39 && \
    conda install faiss-cpu -c pytorch"
# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN /opt/conda/envs/py39/bin/pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app /code/app
COPY ./tests /code/tests

COPY ./.git /code/.git

# INFO, DEBUG, DEBUG_PII
ENV LOGLEVEL="INFO"

WORKDIR /code/tests
