FROM python:3.11-bullseye
WORKDIR /code

 
COPY ./requirements.txt /code/requirements.txt

 
RUN apt-get update && apt-get upgrade -y
RUN apt-get install ca-certificates -y
RUN pip install -r /code/requirements.txt
# 
WORKDIR /code

# 
COPY ./app /code/app
COPY ./tests /code/tests

COPY ./.git /code/.git

# INFO, DEBUG, DEBUG_PII
ENV LOGLEVEL="DEBUG"

WORKDIR /code/tests
