FROM python:3.11-bullseye
WORKDIR /code

 
COPY ./copilot/requirements.txt /code/requirements.txt

 
RUN apt-get update && apt-get upgrade -y
RUN pip install -r /code/requirements.txt

 
COPY ./copilot/app /code/app
COPY ./common /code/app/common
COPY ./copilot/tests /code/tests

COPY ./.git /code/.git

# INFO, DEBUG, DEBUG_PII
ENV LOGLEVEL="DEBUG"

WORKDIR /code/tests
